# Generated by Django 4.1.7 on 2023-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0029_customerlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlogin',
            name='password',
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='password1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='password2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
