# Generated by Django 4.1.7 on 2023-11-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0030_remove_customerlogin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerlogin',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='password2',
        ),
    ]
