# Generated by Django 4.1.7 on 2023-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0031_rename_password1_customerlogin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerlogin',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='password2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
