# Generated by Django 4.1.7 on 2023-11-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0032_rename_password_customerlogin_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
