# Generated by Django 4.1.7 on 2023-11-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0035_remove_customerlogin_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlogin',
            name='password',
        ),
    ]
