# Generated by Django 4.1.7 on 2023-11-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0036_remove_customerlogin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlogin',
            name='phone_number',
        ),
    ]
