# Generated by Django 4.1.7 on 2023-11-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0039_userprofileinfo_delete_customerlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=60)),
                ('password1', models.CharField(blank=True, max_length=30, null=True)),
                ('password2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
