# Generated by Django 4.1.7 on 2023-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0040_customerlogin_delete_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
