# Generated by Django 4.1.7 on 2023-11-29 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0041_customerlogin_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlogin',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customerlogin',
            name='password2',
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=18, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.'), django.core.validators.MaxLengthValidator]),
        ),
    ]
