# Generated by Django 4.1.7 on 2023-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0042_remove_customerlogin_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogin',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
