# Generated by Django 4.1.7 on 2023-11-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0043_customerlogin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogin',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
