# Generated by Django 4.1.7 on 2023-11-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0044_alter_customerlogin_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerLogin',
            new_name='User',
        ),
    ]
