# Generated by Django 4.1.7 on 2023-11-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0045_rename_customerlogin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='eanniversary',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='ebirthday',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='ecafeteria',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='edieting',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='ehotel',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='enaming',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='eplanning',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='erendering',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='ewedding',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='food',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
        migrations.AlterField(
            model_name='ritegallery',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RiteWeb.user'),
        ),
    ]
