# Generated by Django 4.1.7 on 2023-11-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0046_userprofileinfo_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
