# Generated by Django 4.1.7 on 2023-11-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0048_userprofileinfo_username_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
