# Generated by Django 4.1.7 on 2023-11-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0049_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='password',
        ),
    ]
