# Generated by Django 4.1.7 on 2023-11-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0050_remove_userprofileinfo_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
