# Generated by Django 4.1.7 on 2023-11-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiteWeb', '0052_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='location',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
